In [1]:
import pandas as pd
import yfinance as yf
import numpy as np

In [2]:
nifty_500 = pd.read_csv('ind_nifty500list.csv')

In [3]:
nifty_500['Symbol_Yahoo'] = nifty_500['Symbol'].apply(lambda x : '{}.{}'.format(x,'NS'))

In [4]:
nifty_500['Symbol'].apply(lambda x : '{}.{}'.format(x,'NS')).tolist()

['3MINDIA.NS',
 'ACC.NS',
 'AIAENG.NS',
 'APLAPOLLO.NS',
 'AUBANK.NS',
 'AARTIIND.NS',
 'AAVAS.NS',
 'ABBOTINDIA.NS',
 'ADANIGAS.NS',
 'ADANIGREEN.NS',
 'ADANIPORTS.NS',
 'ADANIPOWER.NS',
 'ADANITRANS.NS',
 'ABCAPITAL.NS',
 'ABFRL.NS',
 'ADVENZYMES.NS',
 'AEGISCHEM.NS',
 'AFFLE.NS',
 'AJANTPHARM.NS',
 'AKZOINDIA.NS',
 'APLLTD.NS',
 'ALKEM.NS',
 'ALLCARGO.NS',
 'AMARAJABAT.NS',
 'AMBER.NS',
 'AMBUJACEM.NS',
 'APOLLOHOSP.NS',
 'APOLLOTYRE.NS',
 'ARVINDFASN.NS',
 'ASAHIINDIA.NS',
 'ASHOKLEY.NS',
 'ASHOKA.NS',
 'ASIANPAINT.NS',
 'ASTERDM.NS',
 'ASTRAZEN.NS',
 'ASTRAL.NS',
 'ATUL.NS',
 'AUROPHARMA.NS',
 'AVANTIFEED.NS',
 'DMART.NS',
 'AXISBANK.NS',
 'BASF.NS',
 'BEML.NS',
 'BSE.NS',
 'BAJAJ-AUTO.NS',
 'BAJAJCON.NS',
 'BAJAJELEC.NS',
 'BAJFINANCE.NS',
 'BAJAJFINSV.NS',
 'BAJAJHLDNG.NS',
 'BALKRISIND.NS',
 'BALMLAWRIE.NS',
 'BALRAMCHIN.NS',
 'BANDHANBNK.NS',
 'BANKBARODA.NS',
 'BANKINDIA.NS',
 'MAHABANK.NS',
 'BATAINDIA.NS',
 'BAYERCROP.NS',
 'BERGEPAINT.NS',
 'BDL.NS',
 'BEL.NS',
 'BHARATFORG.NS',
 'BHEL.NS',
 'BPCL.NS',
 'BHARTIARTL.NS',
 'INFRATEL.NS',
 'BIOCON.NS',
 'BIRLACORPN.NS',
 'BSOFT.NS',
 'BLISSGVS.NS',
 'BLUEDART.NS',
 'BLUESTARCO.NS',
 'BBTC.NS',
 'BOMDYEING.NS',
 'BOSCHLTD.NS',
 'BRIGADE.NS',
 'BRITANNIA.NS',
 'CARERATING.NS',
 'CCL.NS',
 'CESC.NS',
 'CRISIL.NS',
 'CADILAHC.NS',
 'CANFINHOME.NS',
 'CANBK.NS',
 'CAPLIPOINT.NS',
 'CGCL.NS',
 'CARBORUNIV.NS',
 'CASTROLIND.NS',
 'CEATLTD.NS',
 'CENTRALBK.NS',
 'CDSL.NS',
 'CENTURYPLY.NS',
 'CERA.NS',
 'CHALET.NS',
 'CHAMBLFERT.NS',
 'CHENNPETRO.NS',
 'CHOLAHLDNG.NS',
 'CHOLAFIN.NS',
 'CIPLA.NS',
 'CUB.NS',
 'COALINDIA.NS',
 'COCHINSHIP.NS',
 'COLPAL.NS',
 'CONCOR.NS',
 'COROMANDEL.NS',
 'CREDITACC.NS',
 'CROMPTON.NS',
 'CUMMINSIND.NS',
 'CYIENT.NS',
 'DBCORP.NS',
 'DCBBANK.NS',
 'DCMSHRIRAM.NS',
 'DLF.NS',
 'DABUR.NS',
 'DALBHARAT.NS',
 'DEEPAKNTR.NS',
 'DELTACORP.NS',
 'DHFL.NS',
 'DBL.NS',
 'DISHTV.NS',
 'DCAL.NS',
 'DIVISLAB.NS',
 'DIXON.NS',
 'LALPATHLAB.NS',
 'DRREDDY.NS',
 'EIDPARRY.NS',
 'EIHOTEL.NS',
 'EDELWEISS.NS',
 'EICHERMOT.NS',
 'ELGIEQUIP.NS',
 'EMAMILTD.NS',
 'ENDURANCE.NS',
 'ENGINERSIN.NS',
 'EQUITAS.NS',
 'ERIS.NS',
 'ESCORTS.NS',
 'ESSELPACK.NS',
 'EXIDEIND.NS',
 'FDC.NS',
 'FEDERALBNK.NS',
 'FMGOETZE.NS',
 'FINEORG.NS',
 'FINCABLES.NS',
 'FINPIPE.NS',
 'FSL.NS',
 'FORTIS.NS',
 'FCONSUMER.NS',
 'FLFL.NS',
 'FRETAIL.NS',
 'GAIL.NS',
 'GEPIL.NS',
 'GET&D.NS',
 'GHCL.NS',
 'GMRINFRA.NS',
 'GALAXYSURF.NS',
 'GARFIBRES.NS',
 'GAYAPROJ.NS',
 'GICRE.NS',
 'GILLETTE.NS',
 'GLAXO.NS',
 'GLENMARK.NS',
 'GODFRYPHLP.NS',
 'GODREJAGRO.NS',
 'GODREJCP.NS',
 'GODREJIND.NS',
 'GODREJPROP.NS',
 'GRANULES.NS',
 'GRAPHITE.NS',
 'GRASIM.NS',
 'GESHIP.NS',
 'GREAVESCOT.NS',
 'GRINDWELL.NS',
 'GUJALKALI.NS',
 'GUJGASLTD.NS',
 'GMDCLTD.NS',
 'GNFC.NS',
 'GPPL.NS',
 'GSFC.NS',
 'GSPL.NS',
 'GULFOILLUB.NS',
 'HEG.NS',
 'HCLTECH.NS',
 'HDFCAMC.NS',
 'HDFCBANK.NS',
 'HDFCLIFE.NS',
 'HFCL.NS',
 'HATSUN.NS',
 'HAVELLS.NS',
 'HEIDELBERG.NS',
 'HERITGFOOD.NS',
 'HEROMOTOCO.NS',
 'HEXAWARE.NS',
 'HSCL.NS',
 'HIMATSEIDE.NS',
 'HINDALCO.NS',
 'HAL.NS',
 'HINDCOPPER.NS',
 'HINDPETRO.NS',
 'HINDUNILVR.NS',
 'HINDZINC.NS',
 'HONAUT.NS',
 'HUDCO.NS',
 'HDFC.NS',
 'ICICIBANK.NS',
 'ICICIGI.NS',
 'ICICIPRULI.NS',
 'ISEC.NS',
 'ICRA.NS',
 'IDBI.NS',
 'IDFCFIRSTB.NS',
 'IDFC.NS',
 'IFBIND.NS',
 'IFCI.NS',
 'IIFL.NS',
 'IRB.NS',
 'IRCON.NS',
 'ITC.NS',
 'ITDCEM.NS',
 'ITI.NS',
 'INDIACEM.NS',
 'ITDC.NS',
 'IBULHSGFIN.NS',
 'IBULISL.NS',
 'IBREALEST.NS',
 'IBVENTURES.NS',
 'INDIAMART.NS',
 'INDIANB.NS',
 'IEX.NS',
 'INDHOTEL.NS',
 'IOC.NS',
 'IOB.NS',
 'INDOSTAR.NS',
 'IGL.NS',
 'INDUSINDBK.NS',
 'INFIBEAM.NS',
 'NAUKRI.NS',
 'INFY.NS',
 'INOXLEISUR.NS',
 'INTELLECT.NS',
 'INDIGO.NS',
 'IPCALAB.NS',
 'JBCHEPHARM.NS',
 'JKCEMENT.NS',
 'JKLAKSHMI.NS',
 'JKPAPER.NS',
 'JKTYRE.NS',
 'JMFINANCIL.NS',
 'JSWENERGY.NS',
 'JSWSTEEL.NS',
 'JAGRAN.NS',
 'JAICORPLTD.NS',
 'JISLJALEQS.NS',
 'J&KBANK.NS',
 'JAMNAAUTO.NS',
 'JINDALSAW.NS',
 'JSLHISAR.NS',
 'JSL.NS',
 'JINDALSTEL.NS',
 'JCHAC.NS',
 'JUBLFOOD.NS',
 'JUBILANT.NS',
 'JUSTDIAL.NS',
 'JYOTHYLAB.NS',
 'KPRMILL.NS',
 'KEI.NS',
 'KNRCON.NS',
 'KPITTECH.NS',
 'KRBL.NS',
 'KAJARIACER.NS',
 'KALPATPOWR.NS',
 'KANSAINER.NS',
 'KTKBANK.NS',
 'KARURVYSYA.NS',
 'KSCL.NS',
 'KEC.NS',
 'KENNAMET.NS',
 'KIRLOSENG.NS',
 'KOLTEPATIL.NS',
 'KOTAKBANK.NS',
 'L&TFH.NS',
 'LTTS.NS',
 'LICHSGFIN.NS',
 'LAXMIMACH.NS',
 'LAKSHVILAS.NS',
 'LTI.NS',
 'LT.NS',
 'LAURUSLABS.NS',
 'LEMONTREE.NS',
 'LINDEINDIA.NS',
 'LUPIN.NS',
 'LUXIND.NS',
 'MASFIN.NS',
 'MMTC.NS',
 'MOIL.NS',
 'MRF.NS',
 'MAGMA.NS',
 'MGL.NS',
 'MAHSCOOTER.NS',
 'MAHSEAMLES.NS',
 'M&MFIN.NS',
 'M&M.NS',
 'MAHINDCIE.NS',
 'MHRIL.NS',
 'MAHLOG.NS',
 'MANAPPURAM.NS',
 'MRPL.NS',
 'MARICO.NS',
 'MARUTI.NS',
 'MFSL.NS',
 'METROPOLIS.NS',
 'MINDTREE.NS',
 'MINDACORP.NS',
 'MINDAIND.NS',
 'MIDHANI.NS',
 'MOTHERSUMI.NS',
 'MOTILALOFS.NS',
 'MPHASIS.NS',
 'MCX.NS',
 'MUTHOOTFIN.NS',
 'NATCOPHARM.NS',
 'NBCC.NS',
 'NCC.NS',
 'NESCO.NS',
 'NHPC.NS',
 'NIITTECH.NS',
 'NLCINDIA.NS',
 'NMDC.NS',
 'NTPC.NS',
 'NH.NS',
 'NATIONALUM.NS',
 'NFL.NS',
 'NBVENTURES.NS',
 'NAVINFLUOR.NS',
 'NESTLEIND.NS',
 'NETWORK18.NS',
 'NILKAMAL.NS',
 'NAM-INDIA.NS',
 'OBEROIRLTY.NS',
 'ONGC.NS',
 'OIL.NS',
 'OMAXE.NS',
 'OFSS.NS',
 'ORIENTCEM.NS',
 'ORIENTELEC.NS',
 'ORIENTREF.NS',
 'PCJEWELLER.NS',
 'PIIND.NS',
 'PNBHOUSING.NS',
 'PNCINFRA.NS',
 'PTC.NS',
 'PVR.NS',
 'PAGEIND.NS',
 'PARAGMILK.NS',
 'PERSISTENT.NS',
 'PETRONET.NS',
 'PFIZER.NS',
 'PHILIPCARB.NS',
 'PHOENIXLTD.NS',
 'PIDILITIND.NS',
 'PEL.NS',
 'POLYCAB.NS',
 'PFC.NS',
 'POWERGRID.NS',
 'PRAJIND.NS',
 'PRESTIGE.NS',
 'PRSMJOHNSN.NS',
 'PGHL.NS',
 'PGHH.NS',
 'PNB.NS',
 'QUESS.NS',
 'RBLBANK.NS',
 'RECLTD.NS',
 'RITES.NS',
 'RADICO.NS',
 'RVNL.NS',
 'RAIN.NS',
 'RAJESHEXPO.NS',
 'RALLIS.NS',
 'RCF.NS',
 'RATNAMANI.NS',
 'RAYMOND.NS',
 'REDINGTON.NS',
 'RELAXO.NS',
 'RELCAPITAL.NS',
 'RELIANCE.NS',
 'RELINFRA.NS',
 'RPOWER.NS',
 'REPCOHOME.NS',
 'RESPONIND.NS',
 'SHK.NS',
 'SBILIFE.NS',
 'SJVN.NS',
 'SKFINDIA.NS',
 'SRF.NS',
 'SADBHAV.NS',
 'SANOFI.NS',
 'SCHAEFFLER.NS',
 'SIS.NS',
 'SFL.NS',
 'SHILPAMED.NS',
 'SHOPERSTOP.NS',
 'SHREECEM.NS',
 'RENUKA.NS',
 'SHRIRAMCIT.NS',
 'SRTRANSFIN.NS',
 'SIEMENS.NS',
 'SOBHA.NS',
 'SOLARINDS.NS',
 'SONATSOFTW.NS',
 'SOUTHBANK.NS',
 'SPANDANA.NS',
 'SPICEJET.NS',
 'STARCEMENT.NS',
 'SBIN.NS',
 'SAIL.NS',
 'SWSOLAR.NS',
 'STRTECH.NS',
 'STAR.NS',
 'SUDARSCHEM.NS',
 'SPARC.NS',
 'SUNPHARMA.NS',
 'SUNTV.NS',
 'SUNCLAYLTD.NS',
 'SUNDARMFIN.NS',
 'SUNDRMFAST.NS',
 'SUNTECK.NS',
 'SUPRAJIT.NS',
 'SUPREMEIND.NS',
 'SUZLON.NS',
 'SWANENERGY.NS',
 'SYMPHONY.NS',
 'SYNGENE.NS',
 'TCIEXP.NS',
 'TCNSBRANDS.NS',
 'TTKPRESTIG.NS',
 'TVTODAY.NS',
 'TV18BRDCST.NS',
 'TVSMOTOR.NS',
 'TAKE.NS',
 'TASTYBITE.NS',
 'TCS.NS',
 'TATACONSUM.NS',
 'TATAELXSI.NS',
 'TATAINVEST.NS',
 'TATAMTRDVR.NS',
 'TATAMOTORS.NS',
 'TATAPOWER.NS',
 'TATASTLBSL.NS',
 'TATASTEEL.NS',
 'TEAMLEASE.NS',
 'TECHM.NS',
 'TECHNOE.NS',
 'NIACL.NS',
 'RAMCOCEM.NS',
 'THERMAX.NS',
 'THYROCARE.NS',
 'TIMETECHNO.NS',
 'TIMKEN.NS',
 'TITAN.NS',
 'TORNTPHARM.NS',
 'TORNTPOWER.NS',
 'TRENT.NS',
 'TRIDENT.NS',
 'TRITURBINE.NS',
 'TIINDIA.NS',
 'UCOBANK.NS',
 'UFLEX.NS',
 'UPL.NS',
 'UJJIVAN.NS',
 'ULTRACEMCO.NS',
 'UNIONBANK.NS',
 'UBL.NS',
 'MCDOWELL-N.NS',
 'VGUARD.NS',
 'VMART.NS',
 'VIPIND.NS',
 'VRLLOG.NS',
 'VSTIND.NS',
 'WABAG.NS',
 'VAIBHAVGBL.NS',
 'VAKRANGEE.NS',
 'VTL.NS',
 'VARROC.NS',
 'VBL.NS',
 'VEDL.NS',
 'VENKEYS.NS',
 'VINATIORGA.NS',
 'IDEA.NS',
 'VOLTAS.NS',
 'WABCOINDIA.NS',
 'WELCORP.NS',
 'WELSPUNIND.NS',
 'WESTLIFE.NS',
 'WHIRLPOOL.NS',
 'WIPRO.NS',
 'WOCKPHARMA.NS',
 'ZEEL.NS',
 'ZENSARTECH.NS',
 'ZYDUSWELL.NS',
 'ECLERX.NS']

In [5]:
nifty_500

,Company Name,Industry,Symbol,Series,ISIN Code,Symbol_Yahoo
0,3M India Ltd.,SERVICES,3MINDIA,EQ,INE470A01017,3MINDIA.NS
1,ACC Ltd.,CEMENT & CEMENT PRODUCTS,ACC,EQ,INE012A01025,ACC.NS
2,AIA Engineering Ltd.,INDUSTRIAL MANUFACTURING,AIAENG,EQ,INE212H01026,AIAENG.NS
3,APL Apollo Tubes Ltd.,METALS,APLAPOLLO,EQ,INE702C01019,APLAPOLLO.NS
4,AU Small Finance Bank Ltd.,FINANCIAL SERVICES,AUBANK,EQ,INE949L01017,AUBANK.NS
...,...,...,...,...,...,...
496,Wockhardt Ltd.,PHARMA,WOCKPHARMA,EQ,INE049B01025,WOCKPHARMA.NS
497,Zee Entertainment Enterprises Ltd.,MEDIA & ENTERTAINMENT,ZEEL,EQ,INE256A01028,ZEEL.NS
498,Zensar Technolgies Ltd.,IT,ZENSARTECH,EQ,INE520A01027,ZENSARTECH.NS
499,Zydus Wellness Ltd.,CONSUMER GOODS,ZYDUSWELL,EQ,INE768C01010,ZYDUSWELL.NS
500,eClerx Services Ltd.,IT,ECLERX,EQ,INE738I01010,ECLERX.NS

In [6]:
Industries = list(nifty_500['Industry'].unique())
Industry_code = [i for i in range(1,len(Industries) + 1)]
Industry_dict = dict(zip(Industries,Industry_code))

In [35]:
Industry_dict

{'SERVICES': 1,
 'CEMENT & CEMENT PRODUCTS': 2,
 'INDUSTRIAL MANUFACTURING': 3,
 'METALS': 4,
 'FINANCIAL SERVICES': 5,
 'CHEMICALS': 6,
 'PHARMA': 7,
 'OIL & GAS': 8,
 'POWER': 9,
 'CONSUMER GOODS': 10,
 'IT': 11,
 'AUTOMOBILE': 12,
 'HEALTHCARE SERVICES': 13,
 'CONSTRUCTION': 14,
 'FERTILISERS & PESTICIDES': 15,
 'TELECOM': 16,
 'MEDIA & ENTERTAINMENT': 17,
 'TEXTILES': 18,
 'PAPER': 19}

In [34]:
sectors = []
nifty_500 = nifty_500.sort_values('Symbol')
for symbol in tqdm(nifty_500['Symbol_Yahoo'].values) :
    sector = nifty_500[nifty_500['Symbol_Yahoo'] == symbol]['Industry'].values[0]
    sectors.append(Industry_dict[sector])

sectors = np.array(sectors)        
np.save('data.npy',sectors)

100%|██████████| 501/501 [00:00<00:00, 1375.51it/s]

In [7]:
start = '2009-05-20'
end = '2020-05-20'

In [8]:
z = yf.Ticker("ITC.NS")
x = yf.Ticker("ADANIGREEN.NS")

In [9]:
z = z.history(start = start,end = end)
x = x.history(start = start,end = end)

In [10]:
x.head()

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date
2018-06-18  30.00  31.50  28.50  31.50  7006229          0             0
2018-06-19  32.70  33.05  31.00  32.60  2895692          0             0
2018-06-20  31.50  32.20  31.00  31.00  1115553          0             0
2018-06-21  29.45  30.00  29.45  29.65  2854524          0             0
2018-06-22  28.20  29.80  28.20  29.45  1612972          0             0

In [11]:
list(z.loc['2019-02-12'].values)

[271.84, 275.23, 269.44, 270.13, 7341352.0, 0.0, 0.0]

In [12]:
list(z.loc['2019-03-28'].values)

[288.57, 296.32, 287.49, 294.36, 17752380.0, 0.0, 0.0]

In [13]:
li1 = x.index.tolist()
li2 = z.index.tolist()

In [14]:
li_dif = [i for i in li1 + li2 if i not in li1 or i not in li2]

In [15]:
temp = []
for date in li_dif:
    temp.append([0,0,0,0,0,0,0])
temp_df = pd.DataFrame(temp,index = li_dif,columns = x.columns)
df = pd.concat([x,temp_df])

In [16]:
df.shape

(2704, 7)

In [17]:
x.shape

(467, 7)

In [18]:
z.shape

(2704, 7)

In [21]:
index = [pd.Timestamp('2009-12-23'),pd.Timestamp('2009-12-24'),pd.Timestamp('2009-12-29'),pd.Timestamp('2009-12-30'),pd.Timestamp('2009-12-31'),pd.Timestamp('2010-11-05'),pd.Timestamp('2011-10-26'),pd.Timestamp('2012-10-26'),pd.Timestamp('2012-11-13'),pd.Timestamp('2014-10-23'),pd.Timestamp('2015-11-11'),pd.Timestamp('2019-02-13'),pd.Timestamp('2019-03-29')]

In [26]:
from tqdm import tqdm

sectors = []

for symbol in tqdm(nifty_500['Symbol_Yahoo'].values) :
    ticker = yf.Ticker(symbol)
    df = ticker.history(start = start,end = end,actions = False)
    
    df.columns = ['open','high','low','close','volume']
    
    if df.shape[0] < z.shape[0] :
        temp1 = []
        li1 = df.index.tolist()
        li2 = z.index.tolist()
        li_dif = [i for i in li1 + li2 if i not in li1 or i not in li2] 
        for date in li_dif:
            temp1.append([0,0,0,0,0])
        temp_df_1 = pd.DataFrame(temp1,index = li_dif,columns = df.columns)
        df = pd.concat([df,temp_df_1])
        df = df.sort_index(axis = 0)
        
    temp = []
    li1 = df.index.tolist()
    li2 = z.index.tolist()
    li_dif_1 = [i for i in li1 + li2 if i not in li1 or i not in li2] 
    df = df.drop(labels = li_dif_1,axis = 0)
    
    temp.append(list(df.loc['2009-12-22'].values))
    temp.append(list(df.loc['2009-12-22'].values))
    temp.append(list(df.loc['2009-12-22'].values))
    temp.append(list(df.loc['2009-12-22'].values))
    temp.append(list(df.loc['2009-12-22'].values))
    temp.append(list(df.loc['2010-11-04'].values))
    temp.append(list(df.loc['2011-10-25'].values))
    temp.append(list(df.loc['2012-10-25'].values))
    temp.append(list(df.loc['2012-11-12'].values))
    temp.append(list(df.loc['2014-10-22'].values))
    temp.append(list(df.loc['2015-11-10'].values))
    temp.append(list(df.loc['2019-02-12'].values))
    temp.append(list(df.loc['2019-03-28'].values))

    temp_df = pd.DataFrame(temp,index = index,columns = df.columns)

    df = pd.concat([df,temp_df])

    df = df.sort_index(axis = 0)
    
    df = df.drop(labels = [pd.Timestamp('2014-04-24'),pd.Timestamp('2014-10-15'),pd.Timestamp('2009-10-13')],axis = 0)
    
    df = df.fillna(method = 'ffill')
    
    df = df.loc[~df.index.duplicated(keep='first')]
    
    df.to_csv('data/daily/{}.csv'.format(nifty_500[nifty_500['Symbol_Yahoo'] == symbol]['Symbol'].values[0]))

100%|██████████| 501/501 [12:34<00:00,  1.51s/it]

In [40]:
ticker = yf.Ticker('BHARTIARTL.NS')
a = ticker.history(start = start,end = end,actions = False)

In [28]:
Industry_dict

{'SERVICES': 1,
 'CEMENT & CEMENT PRODUCTS': 2,
 'INDUSTRIAL MANUFACTURING': 3,
 'METALS': 4,
 'FINANCIAL SERVICES': 5,
 'CHEMICALS': 6,
 'PHARMA': 7,
 'OIL & GAS': 8,
 'POWER': 9,
 'CONSUMER GOODS': 10,
 'IT': 11,
 'AUTOMOBILE': 12,
 'HEALTHCARE SERVICES': 13,
 'CONSTRUCTION': 14,
 'FERTILISERS & PESTICIDES': 15,
 'TELECOM': 16,
 'MEDIA & ENTERTAINMENT': 17,
 'TEXTILES': 18,
 'PAPER': 19}

In [48]:
len(set(z.index.tolist()))

2462

In [49]:
a

              Open    High     Low   Close      Volume
Date
2010-05-20  224.77  229.57  223.73  224.99   4981868.0
2010-05-21  223.91  231.00  217.86  230.13   3688719.0
2010-05-24  231.73  234.58  227.62  230.00   5387893.0
2010-05-25  229.61  233.76  226.54  228.75   5182457.0
2010-05-26  230.82  233.07  224.77  227.93   4225689.0
...            ...     ...     ...     ...         ...
2020-05-13  568.40  569.75  549.30  555.95  21113369.0
2020-05-14  551.10  562.50  535.10  539.85  13180860.0
2020-05-15  543.50  556.90  539.40  554.10  14486140.0
2020-05-18  556.90  559.00  535.20  538.05  21586050.0
2020-05-19  558.50  603.50  557.00  598.80  71908985.0

[2463 rows x 5 columns]